name: user_project_ci
on:
  push:
  pull_request:

jobs:
  hardening:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hardening
        env:
          INTERACTIVE: "false"
          TERM: xterm
          DISPLAY: ""
        run: |
          make harden
