name: user_project_ci
on:
  push:
  pull_request:

jobs:
  hardening:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          make setup
          make install
        env:
          DISABLE_DEPRECATED_MAKEFILE_PROMPT: "1"

      - name: Hardening
        env:
          INTERACTIVE: "false"
          TERM: xterm
          DISPLAY: ""
          DISABLE_DEPRECATED_MAKEFILE_PROMPT: "1"
        run: |
          make harden
